# Generated by Django 2.2 on 2019-04-27 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Code', models.CharField(max_length=255)),
                ('Course_Number', models.CharField(max_length=255)),
                ('Course_Name', models.CharField(max_length=255)),
                ('Credit_Hours', models.PositiveIntegerField(default=0)),
                ('Description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='CourseTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Units', models.PositiveIntegerField(default=0)),
                ('Course_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curriculum.Course')),
            ],
            options={
                'db_table': 'CourseTopics',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('Cur_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Min_Hours', models.PositiveIntegerField(default=0)),
                ('Topic_Category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Curriculum',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Topic',
            },
        ),
        migrations.CreateModel(
            name='CurriculumTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.PositiveIntegerField(default=0)),
                ('Subject_Area', models.CharField(max_length=255)),
                ('Units', models.PositiveIntegerField(default=0)),
                ('Cur_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curriculum.Curriculum')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curriculum.CourseTopics')),
            ],
            options={
                'db_table': 'CurriculumTopic',
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='Head_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curriculum.Person'),
        ),
        migrations.AddField(
            model_name='coursetopics',
            name='Topic_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curriculum.Topic'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('Subject_Code', 'Course_Number'), name='course_unique'),
        ),
        migrations.AddConstraint(
            model_name='curriculumtopic',
            constraint=models.UniqueConstraint(fields=('ID', 'Cur_name'), name='currTopic_unique'),
        ),
        migrations.AddConstraint(
            model_name='coursetopics',
            constraint=models.UniqueConstraint(fields=('Course_Name', 'Topic_ID'), name='courseTopics_unique'),
        ),
    ]
