# Generated by Django 2.2 on 2019-04-27 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('Grade_Distribution_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Grade', models.CharField(max_length=255)),
                ('Person_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curriculum.Person')),
            ],
            options={
                'db_table': 'Grade',
            },
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('Grade_Distribution_ID', 'Person_ID'), name='grade_unique'),
        ),
    ]
