# Generated by Django 2.2 on 2019-05-05 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0002_auto_20190504_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='Grade',
            new_name='Letter_Grade',
        ),
        migrations.RemoveField(
            model_name='coursesection',
            name='Associated_Grade_Distribution',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='Associated_Grade_Dist',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Association_ID',
        ),
        migrations.AddField(
            model_name='grade',
            name='Associated_Course_Section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Curriculum.CourseSection'),
        ),
        migrations.AddField(
            model_name='grade',
            name='Associated_Goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Curriculum.Goal'),
        ),
    ]
