# Generated by Django 2.2 on 2019-05-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0003_auto_20190505_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='dist_number',
            field=models.IntegerField(default=0),
        ),
    ]
