# Generated by Django 2.2 on 2019-04-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0003_auto_20190427_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='Semester',
            field=models.CharField(choices=[('SP', 'Spring semester'), ('SM', 'Summer semester'), ('FA', 'fall semester'), ('WI', 'winter semester')], max_length=255),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='Topic_Category',
            field=models.CharField(choices=[('EX', 'Extensive'), ('IN', 'Inclusive'), ('BP', 'BasicPlus'), ('BC', 'Basic'), ('US', 'Unsatisfactory'), ('SB', 'Substandard')], default='BC', max_length=255),
        ),
        migrations.AlterField(
            model_name='curriculumtopic',
            name='Level',
            field=models.PositiveIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1),
        ),
        migrations.AlterField(
            model_name='grade',
            name='Grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('F', 'Fail'), ('W', 'Withdraw'), ('I', 'Incomplete')], max_length=255),
        ),
    ]
