# Generated by Django 2.2 on 2019-05-04 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0004_auto_20190427_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Required', models.BooleanField()),
                ('Course_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curriculum.Course')),
                ('Cur_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curriculum.Curriculum')),
            ],
            options={
                'db_table': 'CurriculumCourse',
            },
        ),
        migrations.AddConstraint(
            model_name='curriculumcourse',
            constraint=models.UniqueConstraint(fields=('Cur_name', 'Course_Name'), name='curriculumCourse_unique'),
        ),
    ]
