# Generated by Django 2.2 on 2019-05-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curriculum', '0005_auto_20190504_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursegoal',
            old_name='Course_Name',
            new_name='Associated_Course',
        ),
        migrations.RenameField(
            model_name='coursegoal',
            old_name='Goal_ID',
            new_name='Associated_Goal',
        ),
        migrations.RenameField(
            model_name='coursesection',
            old_name='Course_Name',
            new_name='Associated_Course',
        ),
        migrations.RenameField(
            model_name='coursesection',
            old_name='Grade_Distribution_ID',
            new_name='Associated_Grade_Distribution',
        ),
        migrations.RenameField(
            model_name='coursetopics',
            old_name='Course_Name',
            new_name='Associated_Course',
        ),
        migrations.RenameField(
            model_name='coursetopics',
            old_name='Topic_ID',
            new_name='Associated_Topic',
        ),
        migrations.RenameField(
            model_name='curriculum',
            old_name='Head_ID',
            new_name='Head',
        ),
        migrations.RenameField(
            model_name='curriculumcourse',
            old_name='Course_Name',
            new_name='Associated_Course',
        ),
        migrations.RenameField(
            model_name='curriculumcourse',
            old_name='Cur_name',
            new_name='Associated_Curriculum',
        ),
        migrations.RenameField(
            model_name='curriculumtopic',
            old_name='Cur_name',
            new_name='Associated_Curriculum',
        ),
        migrations.RenameField(
            model_name='curriculumtopic',
            old_name='ID',
            new_name='Associated_Topic',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='Cur_Name',
            new_name='Associated_Curriculum',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='Grade_Dist_ID',
            new_name='Associated_Grade_Dist',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='Person_ID',
            new_name='Student',
        ),
    ]
